import Foundation
import OpenGLES
import UIKit

/// Bridges the SwiftUI launcher to the OpenMW engine, which is built as
/// libopenmw.dylib (embedded in the app's Frameworks directory) exporting
/// a C `main`.
///
/// Filesystem layout at runtime:
///  - Bundle/OpenMWAssets            "local" config dir: base openmw.cfg,
///                                   defaults.bin, gamecontrollerdb.txt,
///                                   resources/ (vfs, shaders, lua_api, ...)
///  - Documents/Data Files           user-supplied Morrowind data (via Files app)
///  - Library/Preferences/openmw     generated user openmw.cfg (data + content)
///  - Library/Application Support/openmw   saves etc. (created by the engine)
enum OpenMWLauncher {

    struct GameData {
        let dataPath: URL
        let contentFiles: [String]
        let archives: [String]
    }

    static var documentsURL: URL {
        FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
    }

    static var userConfigURL: URL {
        FileManager.default.urls(for: .libraryDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Preferences/openmw", isDirectory: true)
    }

    static var assetsURL: URL? {
        Bundle.main.resourceURL?.appendingPathComponent("OpenMWAssets", isDirectory: true)
    }

    /// Master files first, in canonical order, then everything else alphabetically.
    private static let masterOrder = ["morrowind.esm", "tribunal.esm", "bloodmoon.esm"]
    private static let contentExtensions: Set<String> = ["esm", "esp", "omwgame", "omwaddon", "omwscripts"]

    /// Looks for game data in Documents/"Data Files", falling back to
    /// Documents itself so users can drop .esm files at the top level.
    static func scanForGameData() -> GameData? {
        let fm = FileManager.default
        let candidates = [
            documentsURL.appendingPathComponent("Data Files", isDirectory: true),
            documentsURL,
        ]
        for dir in candidates {
            guard let names = try? fm.contentsOfDirectory(atPath: dir.path) else { continue }
            let content = names.filter { contentExtensions.contains(($0 as NSString).pathExtension.lowercased()) }
            if !content.isEmpty {
                let archives = names.filter { ($0 as NSString).pathExtension.lowercased() == "bsa" }
                return GameData(dataPath: dir,
                                contentFiles: sortContent(content),
                                archives: sortArchives(archives))
            }
        }
        return nil
    }

    /// Same canonical ordering as content files: the base game's archive
    /// first so expansions and mods can override it.
    private static func sortArchives(_ files: [String]) -> [String] {
        let masterArchives = ["morrowind.bsa", "tribunal.bsa", "bloodmoon.bsa"]
        let masters = masterArchives.compactMap { canonical in
            files.first { $0.lowercased() == canonical }
        }
        let rest = files
            .filter { !masterArchives.contains($0.lowercased()) }
            .sorted { $0.lowercased() < $1.lowercased() }
        return masters + rest
    }

    private static func sortContent(_ files: [String]) -> [String] {
        let masters = masterOrder.compactMap { canonical in
            files.first { $0.lowercased() == canonical }
        }
        let rest = files
            .filter { !masterOrder.contains($0.lowercased()) }
            .sorted { $0.lowercased() < $1.lowercased() }
        return masters + rest
    }

    /// Writes Library/Preferences/openmw/openmw.cfg pointing the engine at the
    /// detected data directory and content files. The bundled base config
    /// (OpenMWAssets/openmw.cfg) chains to this directory via `config="?userconfig?"`.
    static func writeUserConfig(for game: GameData) throws {
        let fm = FileManager.default
        try fm.createDirectory(at: userConfigURL, withIntermediateDirectories: true)

        var cfg = "# Generated by the OpenMW iOS launcher. Edits are overwritten on each launch.\n"
        cfg += "data=\"\(game.dataPath.path)\"\n"
        for archive in game.archives {
            cfg += "fallback-archive=\(archive)\n"
        }
        for file in game.contentFiles {
            cfg += "content=\(file)\n"
        }
        cfg += "encoding=win1252\n"
        // Bink video playback stalls on iOS (the player waits on an audio
        // clock that never advances), freezing the engine on the intro
        // logos. Point the logo entries at a nonexistent file: the video
        // widget logs "Failed to open video" and returns immediately.
        // (An empty fallback value is rejected by the config parser.)
        cfg += "fallback=Movies_Company_Logo,skipped_on_ios.bik\n"
        cfg += "fallback=Movies_Morrowind_Logo,skipped_on_ios.bik\n"
        try cfg.write(to: userConfigURL.appendingPathComponent("openmw.cfg"),
                      atomically: true, encoding: .utf8)

        // Seed user settings once (the engine owns this file afterwards):
        // the post-processing chain's final blit does not reach the screen
        // on iOS yet, so start with it disabled.
        let settingsURL = userConfigURL.appendingPathComponent("settings.cfg")
        if !fm.fileExists(atPath: settingsURL.path) {
            let settings = """
            [Video]
            resolution x = 1280
            resolution y = 720
            [GUI]
            scaling factor = 0.7
            [Post Processing]
            enabled = false
            """
            try settings.write(to: settingsURL, atomically: true, encoding: .utf8)
        }
    }

    enum LaunchError: LocalizedError {
        case assetsMissing
        case dylibMissing
        case dlopenFailed(String)
        case mainMissing

        var errorDescription: String? {
            switch self {
            case .assetsMissing: return "OpenMWAssets folder is missing from the app bundle."
            case .dylibMissing: return "libopenmw.dylib is missing from the app's Frameworks."
            case .dlopenFailed(let msg): return "Could not load the engine: \(msg)"
            case .mainMissing: return "The engine library does not export main()."
            }
        }
    }

    /// gl4es resolves GLES symbols through this hook. It must be a C function
    /// pointer, so the driver handle lives in a global rather than a capture.
    private static var glesDriverHandle: UnsafeMutableRawPointer?

    /// Kept alive for the process lifetime: gl4es's hardware probe needs a
    /// current GL context, and SDL doesn't create one until the engine starts.
    private static var bootstrapGLContext: EAGLContext?

    /// Prepares the gl4es GL translation layer: binds it to Apple's OpenGL ES
    /// driver (the implementation behind the context SDL creates) and runs its
    /// one-time initialization so per-context state exists before the engine's
    /// first GL call. Without this, glGetString crashes on a NULL glstate.
    private static func initializeGL4ES(frameworksPath: String) throws {
        guard let gl = dlopen(frameworksPath + "/libGL.dylib", RTLD_NOW) else {
            throw LaunchError.dlopenFailed(String(cString: dlerror()))
        }

        glesDriverHandle = dlopen("/System/Library/Frameworks/OpenGLES.framework/OpenGLES", RTLD_NOW)

        typealias SetProcAddressFn = @convention(c) (@convention(c) (UnsafePointer<CChar>?) -> UnsafeMutableRawPointer?) -> Void
        typealias InitFn = @convention(c) () -> Void

        if let sym = dlsym(gl, "set_getprocaddress") {
            let setProcAddress = unsafeBitCast(sym, to: SetProcAddressFn.self)
            setProcAddress { name in
                guard let name, let handle = OpenMWLauncher.glesDriverHandle else { return nil }
                return dlsym(handle, name)
            }
        }
        // gl4es's initialization probes the driver (glGetString etc.), which
        // requires a current context — crash otherwise. Same driver as the
        // context SDL creates later, so everything gl4es learns stays valid.
        guard let context = EAGLContext(api: .openGLES2) else {
            throw LaunchError.dlopenFailed("Could not create a bootstrap OpenGL ES context.")
        }
        bootstrapGLContext = context
        EAGLContext.setCurrent(context)

        if let sym = dlsym(gl, "initialize_gl4es") {
            unsafeBitCast(sym, to: InitFn.self)()
        }
    }

    /// Loads libopenmw.dylib and calls its `main`. This call blocks and takes
    /// over the process (SDL creates its own window on top of the launcher),
    /// so it must run on the main thread and is effectively one-way.
    static func launch(game: GameData) throws -> Never {
        guard let assets = assetsURL,
              FileManager.default.fileExists(atPath: assets.appendingPathComponent("openmw.cfg").path)
        else { throw LaunchError.assetsMissing }

        try writeUserConfig(for: game)

        // The engine resolves its "local" (base) configuration from this
        // directory; see components/files/macospath.cpp.
        setenv("OPENMW_LOCAL_CONFIG_DIR", assets.path, 1)
        // OSG on iOS has no plugin bundles; silence plugin path lookups.
        setenv("OSG_LIBRARY_PATH", "", 1)

        guard let fwPath = Bundle.main.privateFrameworksPath else { throw LaunchError.dylibMissing }

        try initializeGL4ES(frameworksPath: fwPath)

        let dylibPath = fwPath + "/libopenmw.dylib"
        guard FileManager.default.fileExists(atPath: dylibPath) else { throw LaunchError.dylibMissing }

        guard let handle = dlopen(dylibPath, RTLD_NOW) else {
            throw LaunchError.dlopenFailed(String(cString: dlerror()))
        }
        guard let sym = dlsym(handle, "main") else { throw LaunchError.mainMissing }

        typealias MainFn = @convention(c) (Int32, UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?) -> Int32
        let engineMain = unsafeBitCast(sym, to: MainFn.self)

        var argv: [UnsafeMutablePointer<CChar>?] = [strdup("openmw"), nil]
        let code = engineMain(1, &argv)
        // The engine returning means the game quit; there is no launcher UI
        // to return to in a meaningful state, so end the process cleanly.
        exit(code)
    }
}
