import Foundation

/// Bridges the SwiftUI launcher to the OpenMW engine, which is built as
/// libopenmw.dylib (embedded in the app's Frameworks directory) exporting
/// a C `main`.
///
/// Filesystem layout at runtime:
///  - Bundle/OpenMWAssets            "local" config dir: base openmw.cfg,
///                                   defaults.bin, gamecontrollerdb.txt,
///                                   resources/ (vfs, shaders, lua_api, ...)
///  - Documents/Data Files           user-supplied Morrowind data (via Files app)
///  - Library/Preferences/openmw     generated user openmw.cfg (data + content)
///  - Library/Application Support/openmw   saves etc. (created by the engine)
enum OpenMWLauncher {

    struct GameData {
        let dataPath: URL
        let contentFiles: [String]
    }

    static var documentsURL: URL {
        FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
    }

    static var userConfigURL: URL {
        FileManager.default.urls(for: .libraryDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Preferences/openmw", isDirectory: true)
    }

    static var assetsURL: URL? {
        Bundle.main.resourceURL?.appendingPathComponent("OpenMWAssets", isDirectory: true)
    }

    /// Master files first, in canonical order, then everything else alphabetically.
    private static let masterOrder = ["morrowind.esm", "tribunal.esm", "bloodmoon.esm"]
    private static let contentExtensions: Set<String> = ["esm", "esp", "omwgame", "omwaddon", "omwscripts"]

    /// Looks for game data in Documents/"Data Files", falling back to
    /// Documents itself so users can drop .esm files at the top level.
    static func scanForGameData() -> GameData? {
        let fm = FileManager.default
        let candidates = [
            documentsURL.appendingPathComponent("Data Files", isDirectory: true),
            documentsURL,
        ]
        for dir in candidates {
            guard let names = try? fm.contentsOfDirectory(atPath: dir.path) else { continue }
            let content = names.filter { contentExtensions.contains(($0 as NSString).pathExtension.lowercased()) }
            if !content.isEmpty {
                return GameData(dataPath: dir, contentFiles: sortContent(content))
            }
        }
        return nil
    }

    private static func sortContent(_ files: [String]) -> [String] {
        let masters = masterOrder.compactMap { canonical in
            files.first { $0.lowercased() == canonical }
        }
        let rest = files
            .filter { !masterOrder.contains($0.lowercased()) }
            .sorted { $0.lowercased() < $1.lowercased() }
        return masters + rest
    }

    /// Writes Library/Preferences/openmw/openmw.cfg pointing the engine at the
    /// detected data directory and content files. The bundled base config
    /// (OpenMWAssets/openmw.cfg) chains to this directory via `config="?userconfig?"`.
    static func writeUserConfig(for game: GameData) throws {
        let fm = FileManager.default
        try fm.createDirectory(at: userConfigURL, withIntermediateDirectories: true)

        var cfg = "# Generated by the OpenMW iOS launcher. Edits are overwritten on each launch.\n"
        cfg += "data=\"\(game.dataPath.path)\"\n"
        for file in game.contentFiles {
            cfg += "content=\(file)\n"
        }
        cfg += "encoding=win1252\n"
        try cfg.write(to: userConfigURL.appendingPathComponent("openmw.cfg"),
                      atomically: true, encoding: .utf8)
    }

    enum LaunchError: LocalizedError {
        case assetsMissing
        case dylibMissing
        case dlopenFailed(String)
        case mainMissing

        var errorDescription: String? {
            switch self {
            case .assetsMissing: return "OpenMWAssets folder is missing from the app bundle."
            case .dylibMissing: return "libopenmw.dylib is missing from the app's Frameworks."
            case .dlopenFailed(let msg): return "Could not load the engine: \(msg)"
            case .mainMissing: return "The engine library does not export main()."
            }
        }
    }

    /// Loads libopenmw.dylib and calls its `main`. This call blocks and takes
    /// over the process (SDL creates its own window on top of the launcher),
    /// so it must run on the main thread and is effectively one-way.
    static func launch(game: GameData) throws -> Never {
        guard let assets = assetsURL,
              FileManager.default.fileExists(atPath: assets.appendingPathComponent("openmw.cfg").path)
        else { throw LaunchError.assetsMissing }

        try writeUserConfig(for: game)

        // The engine resolves its "local" (base) configuration from this
        // directory; see components/files/macospath.cpp.
        setenv("OPENMW_LOCAL_CONFIG_DIR", assets.path, 1)
        // OSG on iOS has no plugin bundles; silence plugin path lookups.
        setenv("OSG_LIBRARY_PATH", "", 1)

        guard let fwPath = Bundle.main.privateFrameworksPath else { throw LaunchError.dylibMissing }
        let dylibPath = fwPath + "/libopenmw.dylib"
        guard FileManager.default.fileExists(atPath: dylibPath) else { throw LaunchError.dylibMissing }

        guard let handle = dlopen(dylibPath, RTLD_NOW) else {
            throw LaunchError.dlopenFailed(String(cString: dlerror()))
        }
        guard let sym = dlsym(handle, "main") else { throw LaunchError.mainMissing }

        typealias MainFn = @convention(c) (Int32, UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?) -> Int32
        let engineMain = unsafeBitCast(sym, to: MainFn.self)

        var argv: [UnsafeMutablePointer<CChar>?] = [strdup("openmw"), nil]
        let code = engineMain(1, &argv)
        // The engine returning means the game quit; there is no launcher UI
        // to return to in a meaningful state, so end the process cleanly.
        exit(code)
    }
}
